# Generated by Django 4.1.7 on 2023-03-17 03:48

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_house'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=users.models.GenerateProfileImagePath()),
        ),
    ]
