# Generated by Django 4.1.7 on 2023-03-17 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_tasklist_attachment_task_task_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tasklist',
            name='name',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
