# Generated by Django 4.1.7 on 2023-03-15 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='notcompleted_tasks_count',
            field=models.IntegerField(default=0),
        ),
    ]
