# Generated by Django 4.1.7 on 2023-03-16 13:03

from django.db import migrations, models
import house.models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_house_notcompleted_tasks_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=house.models.GenerateHouseImagePath()),
        ),
    ]
